name: 'OSS Upload'
description: 'Upload files to Aliyun OSS'
author: 'hardy'
inputs:
  region:
    required: true
    description: the bucket data region location
  access-key-id:
    required: true
    description: access key
  access-key-secret:
    required: true
    description: access secret
  bucket:
    required: true
    description: bucket
  secure:
    required: true
    description: access secret
    default: 'true'
  local-folder:
    required: true
    description: local-folder
    default: dist
  file-pattern:
    required: false
    description: 'File pattern to filter files (e.g., *.zip, *.tar.gz)'
    default: '*'
  repack-version:
    required: false
    description: 'Repack and zip files using this version (format: x.y.z-w). Omit to skip repacking.'
  remote-dir:
    required: true
    description: remote-dir
    default: /
  debug:
    required: false
    description: 'Enable debug logging (true/false)'
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: upload-cloud
  color: green
